### PR TITLE
fix: `IsLiteral` not restrict generics type

### LINKED ISSUE #680: IsLiteral should not require the type to be Primitive but check it internally
Not sure why the IsLiteral type has a restriction, while other literal types don't have (neither do most other types)

```
export type IsLiteral<T extends Primitive> = IsNotFalse<IsLiteralUnion<T>>;
```

should be:

```
export type IsLiteral<T> = T extends Primitive ? IsNotFalse<IsLiteralUnion<T>> : false;
```

### PR DESCRIPTION
**Pull request by Emiyaaaaa**
fix #680

### CODE REVIEW

File: source/is-literal.d.ts [hunk 1]
```diff
@@ -3,6 +3,22 @@ import type {Numeric} from './numeric';
...
+//=> true
+
+IsPrimitive<string>
+//=> true
+
+IsPrimitive<Object>
+//=> false
+```
+ */
+type IsPrimitive<T> = [T] extends [Primitive] ? true : false;
```
Comment (sindresorhus) [inline source/is-literal.d.ts:20]: Can you move this to internal.d.ts? It makes it easier to reuse types and easier to see what should be exported publicly later on.

File: source/is-literal.d.ts [hunk 2]
```diff
@@ -3,6 +3,22 @@ import type {Numeric} from './numeric';
...
+IsPrimitive<'string'>
+//=> true
+
+IsPrimitive<string>
+//=> true
+
+IsPrimitive<Object>
+//=> false
+```
+ */
```
Comment (sindresorhus) [inline source/is-literal.d.ts:19]:
```suggestion
*/
```

File: source/is-literal.d.ts [hunk 3]
```diff
@@ -3,6 +3,22 @@ import type {Numeric} from './numeric';
 import type {IsNotFalse} from './internal';
 import type {IsNever} from './is-never';
 
+/**
+Returns a boolean for whether the given type `T` is Primitive Value or Primitive Type.
```
Comment (sindresorhus) [inline source/is-literal.d.ts:7]:
```suggestion
Returns a boolean for whether the given type is primitive value or primitive type.
```

**Review by sindresorhus — CHANGES_REQUESTED** [review]
