### PR TITLE
Fixes Jsonify on nested objects with only a name property

### LINKED ISSUE #657: Jsonify fails on nested object with name property.
Code here:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKQM4QHbAGYE84C+c2UEIcARDLmAKYC02tqMFA3AFAfV1wQBGAKwByzGLQAmwgIYhacALyIOcVcWBQWALmVq9cDLNo6WUYBgDmKtQQ63uNeQJFjJwiDLmLda7Bu0++gYQMJ7GcKbmVnq29jzygugYAOrAMAAWYd5omDi4ADzOoixuRgB8DryJmADyQsXiUh5G2Ul5hfWuTWFlQA

```
import { Jsonify } from "type-fest";

type objNestedName = {
    first: {
        name: string
    }
}

type objNestedNoName = {
    first: {
        notName: string
    }
}

type jsonWithName = Jsonify<objNestedName>
type jsonObjNestedNoName = Jsonify<objNestedNoName>
```

Note if you mouseover the second one you can see inside the object, but the first one is an empty object. Might be wrong but I am fairly sure name is not a reserved word in typescript or ES6 so would expect this to work.

### PR DESCRIPTION
**Pull request by donovanhiland**
Fixes #657

### CODE REVIEW

File: source/internal.d.ts [hunk 1]
```diff
@@ -189,9 +189,11 @@ type BaseKeyFilter<Type, Key extends keyof Type> = Key extends symbol
...
 	: Type[Key] extends symbol
 		? never
-		: [(...arguments_: any[]) => any] extends [Type[Key]]
-			? never
-			: Key;
+		: Type[Key] extends Record<string, unknown>
+			? Key
+			: [(...arguments_: any[]) => any] extends [Type[Key]]
+				? never
+				: Key;
```
Comment (sindresorhus) [inline source/internal.d.ts:196]: It would be good with a short code comment on the code that handles the name thing for future reference.

**Comment by sindresorhus** [comment]
Thanks :)
