### PR TITLE
`ConditionalPickDeep`: Fix returning `{}` instead of `never` when no keys match

### LINKED ISSUE #1358: `ConditionalPickDeep` returns `{}` instead of `never` when no keys match
Same issue as #1197 but for `ConditionalPickDeep`.

When no keys match the given condition, `ConditionalPickDeep` returns `{}` instead of `never`:

```ts
import type {ConditionalPickDeep} from 'type-fest';

type Example = {
  a: string;
  b: string | boolean;
  c: {
    d: string;
    e: {
      f?: string;
      g?: boolean;
    };
    j: boolean;
  };
};

type NumberPick = ConditionalPickDeep<Example, number>;
//   ^? {} — should be `never`

const test: NumberPick = {
  anything: 'is accepted', // No error, but should be
};
```

`ConditionalPick` is being fixed in #1197. `ConditionalPickDeep` has the same behavior and should be addressed separately since it uses a different internal implementation (`ConditionalExcept`-based).

### PR DESCRIPTION
**Pull request by derodero24**
Fixes #1358

## Summary
- When no keys match the given `Condition` at any depth, `ConditionalPickDeep` previously returned `{}` (empty object type). This allowed any properties to be assigned without type errors.
- Added a `_NeverIfEmpty` helper that checks if the result has no keys and returns `never` in that case. This is applied only at the top level to avoid interfering with the internal recursive `EmptyObject` exclusion logic.
- Updated JSDoc twoslash comment and test cases accordingly.

## Note
This is the deep variant of the same issue fixed in #1359 for `ConditionalPick`.

### CODE REVIEW

File: source/conditional-pick-deep.d.ts [hunk 1]
```diff
@@ -99,11 +99,13 @@ export type ConditionalPickDeep<
...
 	Options extends ConditionalPickDeepOptions = {},
-> = _ConditionalPickDeep<
+> = _NeverIfEmpty<_ConditionalPickDeep<
 	Type,
 	Condition,
 	ApplyDefaultOptions<ConditionalPickDeepOptions, DefaultConditionalPickDeepOptions, Options>
->;
+>>;
+
+type _NeverIfEmpty<Type> = [keyof Type] extends [never] ? never : Type;
```
Comment (som-sm) [inline source/conditional-pick-deep.d.ts]: This is incorrect, because `keyof Type` would be `never` even for unions with _no_ common properties. For example, `ConditionalPickDeep<{a: string} | {b: string}>, string>` should return `{a: string} | {b: string}`, but with this change it returns `never`.


```suggestion
type _NeverIfEmpty<Type> = Type extends EmptyObject ? never : Type;
```
The above is better because it lets `Type` distribute, and `EmptyObject` is preferable to `keyof Type` since `EmptyObject` is already used to achieve the same behavior in nested cases.
https://github.com/sindresorhus/type-fest/blob/3995003ac0ddab36ebd37e8afbaac1652ea68d4b/source/conditional-pick-deep.d.ts#L118

Comment (derodero24) [reply source/conditional-pick-deep.d.ts]: Good catch, fixed. Also added a test for the union case with no common properties.

**Review by som-sm — APPROVED** [review]
