### PR TITLE
`ConditionalPick`: Fix returning `{}` instead of `never` when no keys match

### LINKED ISSUE #1197: Bug ConditionalPick
### Bug description

```typescript
import type { ConditionalPick } from 'type-fest';

interface TestInterface {
  a: string;
}

// TS validates that everything is ok - WHY ? 
// ConditionalPick<TestInterface, number> === {} .....

const test123123123: ConditionalPick<TestInterface, number> = {
  sdfsdfsdf: 'asdasd',
};
```

### PR DESCRIPTION
**Pull request by derodero24**
Fixes #1197

## Summary
- When no keys match the given `Condition`, `ConditionalPick` previously returned `Pick<Base, never>` which resolves to `{}` (empty object type). This allowed any properties to be assigned without type errors.
- Now it checks if `ConditionalKeys` returns `never` using `IsNever`, and returns `never` in that case.
- Added test cases to verify the `never` return behavior.

## Note
The same issue exists in `ConditionalPickDeep` — tracked separately in #1358.

### CODE REVIEW

File: source/conditional-pick.d.ts [hunk 1]
```diff
@@ -38,9 +39,8 @@ type StringKeysOnly = ConditionalPick<Example, string>;
 
 @category Object
 */
-export type ConditionalPick<Base, Condition> = Pick<
-	Base,
-	ConditionalKeys<Base, Condition>
->;
+export type ConditionalPick<Base, Condition> = IsNever<ConditionalKeys<Base, Condition>> extends true
+	? never
+	: Pick<Base, ConditionalKeys<Base, Condition>>;
```
Comment (som-sm) [inline source/conditional-pick.d.ts]:
```suggestion
export type ConditionalPick<Base, Condition> = ConditionalKeys<Base, Condition> extends infer Keys
	? IsNever<Keys> extends true
		? never
		: Pick<Base, Keys & keyof Base>
	: never;
```

Better than repeating `ConditionalKeys<Base, Condition>` twice.

File: test-d/conditional-pick.ts [hunk 2]
```diff
@@ -26,3 +26,10 @@ expectType<{name: string; successes: number; failures: bigint}>(awesomeCondition
 
 declare const exampleConditionalPickWithUndefined: ConditionalPick<Example, string | undefined>;
 expectType<{a: string; c?: string}>(exampleConditionalPickWithUndefined);
+
+// Returns `never` when no keys match the condition
+declare const noMatchingKeys: ConditionalPick<Example, number>;
+expectNever(noMatchingKeys);
+
+declare const noMatchingKeysBoolean: ConditionalPick<{a: string; b: number}, boolean>;
+expectNever(noMatchingKeysBoolean);
```
Comment (som-sm) [inline test-d/conditional-pick.ts]:
```suggestion
declare const noMatchingKeys: ConditionalPick<Example, number>;
expectType<never>(noMatchingKeys);

declare const noMatchingKeysBoolean: ConditionalPick<{a: string; b: number}, boolean>;
expectType<never>(noMatchingKeysBoolean);
```

Use `expectType` instead of `expectNever` because the editor marks all the code after `expectNever` as unreachable (not good DX).

Image

File: source/conditional-pick.d.ts (hunk 1 above)
Comment (derodero24) [reply source/conditional-pick.d.ts]: @som-sm Thanks, updated both. The `infer Keys` approach is much cleaner.
