### PR TITLE
`ConditionalPickDeep`: supports interface

### LINKED ISSUE #773: ConditionalPickDeep does not work with deep interfaces
Hi,

If the deep property is an interface, `ConditionalPickDeep` does not pick the nested attribute.

Example:

```ts
type S = "SOME STRING";

interface B {
  b: S;
}

interface C {
  b: B;
  c: S;
}

type Test = ConditionalPickDeep<C, S>;

// Expected: type Test = { b: B, c: S }
// Actual: type Test = { c: S }
```

However the code below works as expected:

```ts
type S = "SOME STRING";

type B = {
  b: S;
}

interface C {
  b: B;
  c: S;
}

type Test = ConditionalPickDeep<C, S>;

// Expected: type Test = { b: B, c: S }
// Actual: type Test = { b: B, c: S }
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/773">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/773/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by Emiyaaaaa**
- Fixed #773

### CODE REVIEW

File: source/internal.d.ts [hunk 1]
```diff
@@ -76,6 +77,16 @@ Matches non-recursive types.
 */
 export type NonRecursiveType = BuiltIns | Function | (new (...args: any[]) => unknown);
 
+/**
+Returns a boolean for whether the given type is a normal key-value object.
+*/
+export type IsRecordObject<T> =
```
Comment (sindresorhus) [inline source/internal.d.ts:83]: `Record` is a type, so the expectation is that this would detect such type, which I don't think it does exactly. Maybe a better name would be `IsPlainObject`?

File: source/internal.d.ts [hunk 2]
```diff
@@ -76,6 +77,16 @@ Matches non-recursive types.
 */
 export type NonRecursiveType = BuiltIns | Function | (new (...args: any[]) => unknown);
 
+/**
+Returns a boolean for whether the given type is a normal key-value object.
```
Comment (sindresorhus) [inline source/internal.d.ts:81]: It has to be more specific what a "normal key-value object" is exactly. Plain object?

File: source/internal.d.ts [hunk 3]
```diff
@@ -76,6 +77,16 @@ Matches non-recursive types.
...
+*/
+export type IsRecordObject<T> =
+	T extends NonRecursiveType | UnknownArray | ReadonlyMap<unknown, unknown> | ReadonlySet<unknown>
```
Comment (sindresorhus) [inline source/internal.d.ts:84]: What about WeakMap and other types? I feel like it would be better to come up with a check that didn't need an "exclude list" of types.

**Review by sindresorhus — CHANGES_REQUESTED** [review]
