### PR TITLE
`SetOptional`/`SetRequired`/`SetReadonly`: Fix instantiations with index signatures

### LINKED ISSUE #1013: `SetOptional` remove properties of types with index signatures
### Bug description

After #1007, `SetOptional` remove properties of types with index signatures.

v4.30.1 works fine.

image

### Repro

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nAyimB5MGYCAOwEMAbOAXzgDMoIQ4ByJVAWjpQGcYWA3ACghwEjBRQ6ZAMZoAYhAgYhcNfSUAuOHyhiA5sPVwA2gA9tugwF1tAVxIBrEhADuJYdRHs0BOAF5sXAIiUkoAHkUIABpWOiUWAD4jOAB6VLgAPQB+ETV0uABRM1QZCQATbR84P0DMeIhsyxg9En04AB84B3KUOjEUcoFTCx0Wm3snF3caISA

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/1013">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/1013/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by som-sm**
Fixes #1013

- Tweaked the implementation of `DistributedPick` so that it handles `any` properly
- `Set-*` types now use `DistributedPick` instead of `Except`/`Exclude` combination

### CODE REVIEW

File: source/distributed-pick.d.ts [hunk 1]
```diff
@@ -80,6 +80,4 @@ if (pickedUnion.discriminant === 'A') {
 @category Object
 */
 export type DistributedPick<ObjectType, KeyType extends KeysOfUnion<ObjectType>> =
-	ObjectType extends unknown
```
Comment (som-sm) [inline source/distributed-pick.d.ts:83]: This conditional is no longer required, because the implementation now uses a homomorphic mapped types, which already distributes over union types.

File: source/set-optional.d.ts [hunk 2]
```diff
@@ -32,6 +34,6 @@ export type SetOptional<BaseType, Keys extends keyof BaseType> =
 		// Pick just the keys that are readonly from the base type.
 		Except<BaseType, Keys> &
 		// Pick the keys that should be mutable from the base type and make them mutable.
-		Partial<Except<BaseType, Exclude<keyof BaseType, Keys>>>
+		Partial<DistributedPick<BaseType, Keys & KeysOfUnion<BaseType>>>
```
Comment (som-sm) [inline source/set-optional.d.ts:37]: Would not require intersection with `KeysOfUnion<BaseType>` once #1009 is finalised.

cc: @Emiyaaaaa

**Comment by som-sm** [comment]
**Note:** The updated implementation of `DistributedPick` introduces subtle changes in it's behaviour, which might be problematic if the goal is to keep `DistributedPick` fully aligned with the built-in `Pick` for non-union types.

#### 1. Behaviour with primitives
```ts
// Previous behaviour
type Test = Pick<string, 'toUpperCase'>;
//   ^? type Test = { toUpperCase: () => string }
```
```ts
// Updated behaviour
type Test = Pick<string, 'toUpperCase'>;
//   ^? type Test = string
```
And this happens because homomorphic mapped types pass through primitives unchanged.

#### 2. Picking `number` from `string` indexor
```ts
// Previous behaviour
type Test = Pick<{ [k: string]: unknown }, number>;
//   ^? type Test = { [x: number]: unknown; }
```

```ts
// Updated behaviour
type Test = Pick<{ [k: string]: number }, number>;
//   ^? type Test = {}
```

<br>

@sindresorhus If you think this might create issues, then I'd create a separate internal `Pick` type instead of modifying `DistributedPick`.

**Comment by sindresorhus** [comment]
I think it would be better to create an internal pick type for now.

Do you think the new behavior is the correct one / better? If so, we could consider changing it in v5: https://github.com/sindresorhus/type-fest/issues/450

Alternatively, if both the old and new behavior makes sense in different situations, we could consider adding an option to the type.

**Comment by som-sm** [comment]
It’s hard to determine which behaviour is better, as these are very rare scenarios.

While we could add an option for this, I doubt it'd be very useful—it might just create confusion. Currently, `DistributedPick` does what it says, it distributes `Pick`, but introducing additional changes might not be that obvious.

For now, I'll create an internal `Pick`.

**Comment by sindresorhus** [comment]
@som-sm Nice work! You have done a lot of great work here lately. Would you be interested in being added as a maintainer? No worries if not :)

**Comment by som-sm** [comment]
@sindresorhus Yeah sure, I’d be happy to help as a maintainer and contribute further.

**Comment by sindresorhus** [comment]
Awesome 🎉
