### PR TITLE
Fix `Merge` with optional `any` value

### LINKED ISSUE #506: `Merge` merges optional `any` incorrectly
In version 3.1.0, `Merge` works incorrectly

```ts
type Merged = Merge<{ someKey?: any }, { anotherKey: true }>;

// Before
type Merged = { someKey?: any; anotherKey: true }

// Now
type Merged = { someKey: any; anotherKey: true }
```

`someKey` now becomes required.

### LINKED ISSUE #579: Incorrect `Merge` with optional `any` fields
Hi!

First of all, sorry for my english 🤷‍♂️

I found a problem with incorrect merging of types with optional `any` fields.
Tested on version `3.7.0`.

Current `Merge` type is:
```
type Merge<Destination, Source> = EnforceOptional<
    SimpleMerge<PickIndexSignature<Destination>, PickIndexSignature<Source>>
    & SimpleMerge<OmitIndexSignature<Destination>, OmitIndexSignature<Source>>>;
```
and next code gives us type with all required fields:
```
type DestinationWithOptionalAnyKeys = {
	a?: any;
	c: string;
	d?: any;
	e: number;
};
type SourceWithOptionalAnyKeys = {
	b?: any;
	c?: any;
	d: number;
};
type DestinationSourceWithOptionalAnyKeys = Merge<DestinationWithOptionalAnyKeys, SourceWithOptionalAnyKeys>;

declare const destinationSourceWithOptionalAnyKeys: DestinationSourceWithOptionalAnyKeys;
// destinationSourceWithOptionalAnyKeys => {
//      a: any,
//      b: any,
//      c: any,
//      d: number,
//      e: number
//  }
```
The problem is that the `Merge` try set optional fields with `EnforceOptional`, which makes optional only `* | undefined` fields.
But fields with any other types will stay required.

So, if we rewrite `Merge` type as:
```
type Merge<Destination, Source> =
    EnforceOptional<
        // At this point we set all fields except required as optional
        SetOptional<
            SimpleMerge<PickIndexSignature<Destination>, PickIndexSignature<Source>>
            & SimpleMerge<OmitIndexSignature<Destination>, OmitIndexSignature<Source>>,
            Exclude<
                OptionalKeysOf<PickIndexSignature<Destination> & OmitIndexSignature<Destination>>
                | OptionalKeysOf<PickIndexSignature<Source> & OmitIndexSignature<Source>>,
                RequiredKeysOf<PickIndexSignature<Source> & OmitIndexSignature<Source>>>>>;
```
we will get the correct result:
```
// destinationSourceWithOptionalAnyKeys => {
//     d: number,
//     e: number,
//     a?: any,
//     b?: any,
//     c?: any
// }
```

It solves a problem with optional `any` type fields, but gives "Type instantiation is excessively deep and possibly infinite" error at `MergeDeep` type in tests:

Снимок экрана 2023-03-26 в 01 07 55

Снимок экрана 2023-03-26 в 01 09 59

Variables `fooBarTupleSpread` and `fooBarTupleReplace` casts to `any` type because of this error.

Does anyone have any ideas, how can i fix it?

### PR DESCRIPTION
**Pull request by skarab42**
Fix #506
Fix #579

(Sorry for the delay, I don't have much time with my new job.)

### CODE REVIEW

File: source/merge.d.ts [hunk 1]
```diff
@@ -1,15 +1,12 @@
 import type {OmitIndexSignature} from './omit-index-signature';
 import type {PickIndexSignature} from './pick-index-signature';
 import type {EnforceOptional} from './enforce-optional';
+import type {Simplify} from './simplify';
```
Comment (sindresorhus) [inline source/merge.d.ts:4]: Unused

**Comment by sindresorhus** [comment]
Thanks for fixing :)
