### PR TITLE
`ArraySlice` / `StringSlice`: Fix behaviour with unions

### LINKED ISSUE #1289: `StringSlice` is incorrect for union of string literals of different lengths
### Bug description

It ends up cutting all strings down to the length of the shortest string

### Repro

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgZRlYA7A5sgNsAYwFM4BfOAMyghDgHIYBPMIgWgqIGcY6AoXpixT5iAEzgBeFGkw4RRADx0AhgDoAFkVy4IdOAB96agO4RjdADRwATAD5ecR44D0zuAD0A-A6dxerlHUIAFdccQAjEjpNbV0DelNzIA

### PR DESCRIPTION
**Pull request by som-sm**
Fixes behaviour of `ArraySlice` with unions.

```ts
type Current = ArraySlice<[0, 1, 2, 3], 1, 2 | 3>;
//=> [1]

type Fixed = ArraySlice<[0, 1, 2, 3], 1, 2 | 3>;
//=> [1] | [2]
```

```ts
type Current1= ArraySlice<[0, 1, 2, 3], 2 | -3, 3>;
//=> []

type Updated = ArraySlice<[0, 1, 2, 3], 2 | -3, 3>;
//=> [2] | [1, 2]
```

<br>

This also fixes behaviour of `StringSlice` (Fixes #1289) with unions as it relies on `ArraySlice`, just needed the default type parameters to be fixed.

### CODE REVIEW

File: source/array-slice.d.ts [hunk 1]
```diff
@@ -60,13 +61,33 @@ export type ArraySlice<
...
+				: never // Never happens
+		: IsNever<End> extends true
+			? Start extends unknown // To distribute `Start`
+				? _ArraySlice<Array_, Start, End>
+				: never // Never happens
+			: Start extends unknown // To distribute `Start`
+				? End extends unknown // To distribute `End`
+					? _ArraySlice<Array_, Start, End>
+					: never // Never happens
+				: never // Never happens
```
Comment (som-sm) [inline source/array-slice.d.ts:78]: This is complicated/verbose because the default value of `Start`/`End` is `never`, so we have to explicitly check for `never` before distributing, which introduces several branching cases.

<br>

I guess the reason for having the default value as `never` was that if `End` were simply `Array_["length"]`, then union instantiations of `End` would give incorrect results. 

For example,
`ArraySlice<[0, 1, 2] | [0, 1], 0>` would become
`ArraySlice<[0, 1, 2] | [0, 1], 0, 3 | 2>`,
which would then distribute to
`ArraySlice<[0, 1, 2], 3 | 2> | ArraySlice<[0, 1], 3 | 2>`,
and finally to
`ArraySlice<[0, 1, 2], 3> | ArraySlice<[0, 1, 2], 2> | ArraySlice<[0, 1], 3> | ArraySlice<[0, 1], 2>`,
which would be incorrect.

However, if we set the default for `End` to `UnionMax<Array_["length"]>`, that would fix this issue. The only thing is that explicitly passing `never` would no longer behave the same as omitting the argument. But that’s probably acceptable because `never` shouldn’t really be a valid value for `Start`/`End` anyway. In such cases, we can just return something like `readonly unknown[]` or `[]`.

Comment (som-sm) [reply source/array-slice.d.ts:78]: > However, if we set the default for `End` to `UnionMax<Array_["length"]>`, that would fix this issue. The only thing is that explicitly passing `never` would no longer behave the same as omitting the argument. But that’s probably acceptable because `never` shouldn’t really be a valid value for `Start`/`End` anyway. In such cases, we can just return something like `readonly unknown[]` or `[]`.

@sindresorhus If this is fine, then I'll open a separate PR for this.

Comment (sindresorhus) [reply source/array-slice.d.ts:78]: Yes, seems fine.
