### PR TITLE
`KeysOfUnion`: Fix assignability with `keyof`

### LINKED ISSUE #1008: Assignability b/w generic `keyof T` and `KeysOfUnion<T>`
Ideally, `keyof T` _should_ be assignable to `KeysOfUnion<T>` and `KeysOfUnion<T>` _should not_ be assignable to `keyof T`.

However, currently the exactly opposite happens.

```ts
import { KeysOfUnion } from "type-fest";

// KeysOfUnion<T> should not be assignable to keyof T
type Assignability1<T, K extends keyof T> = unknown;
type Test1<T> = Assignability1<T, KeysOfUnion<T>>; // should error but doesn't

// keyof T should be assignable to KeysOfUnion<T>
type Assignability2<T, K extends KeysOfUnion<T>> = unknown;
type Test2<T> = Assignability2<T, keyof T>; // shouldn't error but does
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/1008">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/1008/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by som-sm**
Fixes #1008

To make `keyof T` assignable to `KeysOfUnion<T>`, we can simply add an union with `keyof ObjectType` to the existing type, as shown below. 

```ts
type KeysOfUnion<ObjectType> =
 | keyof ObjectType
 | ObjectType extends unknown ? keyof ObjectType : never;
```

However, I couldn’t find a straightforward way to prevent `KeysOfUnion<T>` from being assignable to `keyof T`. So, I reworked the implementation to use `UnionToIntersection`, which resolves both issues.

<hr>

There's another hack I figured out while experimenting, this also solves both the issues, but it's very hacky:
```ts
type KeysOfUnion<ObjectType> =
  | keyof ObjectType // Convinces TS that keyof T is part of KeysOfUnion<T>
  | ObjectType extends unknown ? keyof ObjectType: never
  | Extract<Uppercase<string>, Lowercase<ObjectType & string>>; // Convinces TS that KeysOfUnion<T> is broader than keyof T

// keyof T should be assignable to KeysOfUnion<T>
type Assignability2<T, K extends KeysOfUnion<T>> = unknown;
type Test2<T> = Assignability2<T, keyof T>; // doesn't error now

// KeysOfUnion<T> should not be assignable to keyof T
type Assignability1<T, K extends keyof T> = unknown;
type Test1<T> = Assignability1<T, KeysOfUnion<T>>; // does error now
```
[Playground](https://tsplay.dev/mZRl4m)

### CODE REVIEW

File: source/keys-of-union.d.ts [hunk 1]
```diff
@@ -35,6 +37,6 @@ type AllKeys = KeysOfUnion<Union>;
 
 @category Object
 */
-export type KeysOfUnion<ObjectType> = ObjectType extends unknown
-	? keyof ObjectType
-	: never;
+export type KeysOfUnion<ObjectType> =
+  // Hack to fix https://github.com/sindresorhus/type-fest/issues/1008
```
Comment (Emiyaaaaa) [inline source/keys-of-union.d.ts:41]: Is there a way not hack?

File: test-d/keys-of-union.ts [hunk 2]
```diff
@@ -35,3 +35,25 @@ type Expected2 = 'common' | 'a' | 'b' | 'c';
 declare const actual2: KeysOfUnion<Example2>;
 
 expectType<Expected2>(actual2);
+
+// With property modifiers
+declare const actual3: KeysOfUnion<{a?: string; readonly b: number} | {a: number; b: string}>;
+expectType<'a' | 'b'>(actual3);
+
+// KeysOfUnion<T> should NOT be assignable to keyof T
+type Assignability1<T, _K extends keyof T> = unknown;
```
Comment (Emiyaaaaa) [inline test-d/keys-of-union.ts:44]: add test:
```ts
type Assignability1<T extends UnknownRecord, K extends keyof T> = unknown;
type Test1<T extends UnknownRecord> = Assignability1<T, KeysOfUnion<T>>; // should error
```

**Review by Emiyaaaaa — CHANGES_REQUESTED** [review]

File: test-d/keys-of-union.ts (hunk 2 above)
Comment (som-sm) [reply test-d/keys-of-union.ts:44]: @Emiyaaaaa The test you suggested doesn’t seem to produce an error:

```ts
type Assignability5<T extends UnknownRecord, _K extends keyof T> = unknown;
type Test5<T extends UnknownRecord> = Assignability5<T, KeysOfUnion<T>>; // doesn't error
```

<br>

However, adding slightly different constraints does produce the expected error:
```ts
type Assignability5<T extends Record<string, unknown>, _K extends keyof T> = unknown;
// @ts-expect-error
type Test5<T extends Record<string, unknown>> = Assignability5<T, KeysOfUnion<T>>; // Does error
```

```ts
type Assignability5<T extends object, _K extends keyof T> = unknown;
// @ts-expect-error
type Test5<T extends object> = Assignability5<T, KeysOfUnion<T>>; // Does error
```

Comment (Emiyaaaaa) [reply test-d/keys-of-union.ts:44]: I don't have idea right now, maybe it's a bug of Typescript I'm not sure. I'll try to look into this interesting issue later

File: source/keys-of-union.d.ts (hunk 1 above)
Comment (sindresorhus) [reply source/keys-of-union.d.ts:41]: I think it's fine to do this for now until we come up with a better solution.

File: test-d/keys-of-union.ts (hunk 2 above)
Comment (som-sm) [reply test-d/keys-of-union.ts:44]: @sindresorhus These tests don't use either `tsd` or `expect-type`, they are just simple generics, like this:

```ts
type Assignability5<T extends Record<string, unknown>, _K extends keyof T> = unknown;
// @ts-expect-error
type Test5<T extends Record<string, unknown>> = Assignability5<T, KeysOfUnion<T>>; // Does error
```

File: source/keys-of-union.d.ts (hunk 1 above)
Comment (som-sm) [reply source/keys-of-union.d.ts:41]: Yeah, I agree! 
And this is probably a bug, refer [this comment](https://github.com/microsoft/TypeScript/issues/60815#issuecomment-2553605416).

File: test-d/keys-of-union.ts (hunk 2 above)
Comment (sindresorhus) [reply test-d/keys-of-union.ts:44]: Ok, maybe just add your tests, and then add `type Assignability5<T extends UnknownRecord, _K extends keyof T> = unknown;
type Test5<T extends UnknownRecord> = Assignability5<T, KeysOfUnion<T>>; // Doesn't error` commented out with a comment that says that they don't produce error even though they should.

Comment (som-sm) [reply test-d/keys-of-union.ts:44]: Yup makes sense, added all the above mentioned cases and some more, refer [2629884](https://github.com/sindresorhus/type-fest/pull/1009/commits/26298846cd99341d4772a665daa6a031d0746cac).
