### PR TITLE
`MergeDeep`: Remove extra `undefined` from optional properties

### LINKED ISSUE #1314: merge-deep: wrong types inferred when using partial interfaces
### Bug description

**the correct operation of this utility depends on the order of types!**

Let's say there is `interface Pokemon` like this:

```typescript
import type {MergeDeep} from 'type-fest';

interface Pokemon {
      name: string;
      type: string;
    }
```

**valid** :
```typescript
    const testThroughAssert: Pokemon = {} as MergeDeep<
      Partial<Pokemon>,
      Pokemon
    >;
```
=> `success`

**invalid**:
```typescript
    const testThroughAssert: Pokemon = {} as MergeDeep<
      Pokemon,
      Partial<Pokemon>
    >;
```
=> `error TS2322: Type '{ name?: string | undefined; type?: string | undefined; }' is not assignable to type 'Pokemon'.`

### Repro

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3gWRVA5igERRTAF84AzKCEOAciVQFoKUBnGOgbgFgAofsAB2MHBQCGAYzQAFCAGsUICEIz84GzUPEgUALjgcow3Lz6bNjfYZjGhp9ZtL9+klRwTsYAFQAW1AFdcXwBBNjYcGAM5RWVVAF4McnE2OGw8QmIwAB5HCxilFQAaPM0ZcVhgcQAbbIK4gD5Shq4gA

### PR DESCRIPTION
**Pull request by taiyakihitotsu**
Close #1314

(Updated the entire comment.)

This PR is a small change, but it consists of two parts.

## Part 1
```typescript
import type {MergeDeep} from 'type-fest';

interface Pokemon {
      name: string;
      type: string;
    }
```

`MergeDeep<Pokemon, Partial<Pokemon>>` should be equivalent to `Partial<Pokemon>` according to this comment in `merge-deep.d.ts`:
https://github.com/sindresorhus/type-fest/blob/c671aa2e9dbbfb502fde09859286d0caf499eb7a/source/merge-deep.d.ts#L386

However, before this PR, the result type was:
```typescript
{
  name?: string | undefined;
  type?: string | undefined;
}
```

which causes the following error (in the issue):
```
error TS2322: Type '{ name?: string | undefined; type?: string | undefined; }' is not assignable to type 'Pokemon'.
```
(Note: The above is a direct quote from an issue comment. In this case, it seems appropriate to type it as `Partial<Pokemon>` instead of `Pokemon`.)

This extra `| undefined` is unnecessary here.
This PR removes that redundancy with the following change:
https://github.com/sindresorhus/type-fest/pull/1319/files#diff-5ce63d84bd0497ef6dd72ef89147e7bf80f464a1185b1a34139c6c1cb6c37ee5R36

## Part 2
After the change in Part 1, this test doesn't pass:
https://github.com/sindresorhus/type-fest/blob/c671aa2e9dbbfb502fde09859286d0caf499eb7a/test-d/merge-deep.ts#L325

`Required` is added to fix this:
https://github.com/sindresorhus/type-fest/pull/1319/files#diff-5ce63d84bd0497ef6dd72ef89147e7bf80f464a1185b1a34139c6c1cb6c37ee5R61

## Note
The issue described above may be related to PR #1209, which has been suspended since August 31.
I intentionally did not include any changes related to that PR in order to keep this change minimal.

If these changes are considered inappropriate due to the context of PR #1209, I’m fine with closing this PR.

### CODE REVIEW

File: test-d/merge-deep.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ expectType<{
 		fooBar: boolean;
 		items: number[];
 	} | undefined;
-}>(fooBarWithOptional);
+}>);
```
Comment (som-sm) [inline test-d/merge-deep.ts]: Is this change necessary?

File: test-d/merge-deep.ts [hunk 2]
```diff
@@ -309,3 +309,35 @@ expectType<[Bar, FooBarReplace, ...FooBarReplace[]]>(tupleIntoTupleWithVariadicR
 
 declare const tupleIntoTupleWithVariadicReplaceReversed: MergeDeep<[Foo, ...Foo[]], [number, Bar, ...Bar[]], {arrayMergeMode: 'replace'; recurseIntoArrays: true}>;
 expectType<[number, FooBarReplace, ...FooBarReplace[]]>(tupleIntoTupleWithVariadicReplaceReversed);
+
+// Test for https://github.com/sindresorhus/type-fest/issues/1314
```
Comment (som-sm) [inline test-d/merge-deep.ts]: Remove this comment, these tests are unrelated to #1314 (refer https://github.com/sindresorhus/type-fest/issues/1314#issuecomment-3744593004).

File: test-d/merge-deep.ts [hunk 3]
```diff
@@ -309,3 +309,35 @@ expectType<[Bar, FooBarReplace, ...FooBarReplace[]]>(tupleIntoTupleWithVariadicR
...
+	type: string;
+	b: {bb?: string; cc: string};
+};
+type RecordPartial = Partial<RecordNotPartial>;
+
+type testOptionalRecordReplacedByRecord = MergeDeep<RecordPartial, RecordNotPartial>;
+expectType<true>({} as IsEqual<RecordNotPartial, testOptionalRecordReplacedByRecord>);
+
+type testRecordReplacedByOptionalRecord = MergeDeep<RecordNotPartial, RecordPartial>;
+expectType<true>({} as IsEqual<RecordPartial, testRecordReplacedByOptionalRecord>);
```
Comment (som-sm) [inline test-d/merge-deep.ts]:
```suggestion
expectType<RecordNotPartial>({} as MergeDeep<RecordPartial, RecordNotPartial>);
expectType<RecordPartial>({} as MergeDeep<RecordNotPartial, RecordPartial>);
```

File: test-d/merge-deep.ts [hunk 4]
```diff
@@ -309,3 +309,35 @@ expectType<[Bar, FooBarReplace, ...FooBarReplace[]]>(tupleIntoTupleWithVariadicR
...
+	name: string;
+	type: string;
+	b: {bb: string; cc: string | undefined};
+};
+
+type testExpectedNotOptional = MergeDeep<NodeOptional, NodeNotOptional>;
+expectType<true>({} as IsEqual<NodeNotOptional, testExpectedNotOptional>);
+
+type testExpectedOptional = MergeDeep<NodeNotOptional, NodeOptional>;
+expectType<true>({} as IsEqual<NodeOptional, testExpectedOptional>);
```
Comment (som-sm) [inline test-d/merge-deep.ts]: If I understand the need for these cases correctly, I think the following is better and simpler:

```suggestion
expectType<{a: string | undefined; b?: number; c?: boolean | undefined}>(
	{} as MergeDeep<{a: string; b: number; c: boolean}, {a: string | undefined; b?: number; c?: boolean | undefined}>,
);
```

In any case, we need a case that ensures explicitly specified `undefined`s (`{a?: string | undefined}`) in optional properties are preserved.

**Review by som-sm — COMMENTED** [review]
@taiyakihitotsu Added few comments!

File: test-d/merge-deep.ts (hunk 2 above)
Comment (taiyakihitotsu) [reply test-d/merge-deep.ts]: Addressed.

File: test-d/merge-deep.ts (hunk 3 above)
Comment (taiyakihitotsu) [reply test-d/merge-deep.ts]: Addressed.

File: test-d/merge-deep.ts (hunk 1 above)
Comment (taiyakihitotsu) [reply test-d/merge-deep.ts]: Sorry, No.

In my previous environment, this caused a compile-time error that the LSP did not catch.
Now that the issue is resolved, I’ve reverted to the original one.

File: test-d/merge-deep.ts (hunk 4 above)
Comment (taiyakihitotsu) [reply test-d/merge-deep.ts]: Thanks, I missed this case!
(And I've added the reversed case.)

**Comment by taiyakihitotsu** [comment]
@som-sm
Thanks for your review!
I’ve addressed all of your comments.
