### PR TITLE
`DelimiterCase` / `SnakeCase` / `ScreamingSnakeCase` / `KebabCase`: Fix instantiations containing punctuations

### LINKED ISSUE #1074: KebabCasedProperties transforming `:` to `-:`
### Bug description

The `KebabCasedProperties` is hyphening before colons. I would expect the property name `onDialog:close` to become `on-dialog:close`, not `on-dialog-:close`.

### Repro

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nA0igRgQ1wGF8BnFAEwAUoJVZgVS4BfOAM1pDgHIlUAtOyYweAbgCwAKGnAAdjBRR2+AMZoAYhAgZpcfbwhyAIsHwAbCAHMAXKsvkeNuAAoAlHAC8APjgA3CGAKSSkWEOl+NAAhfCgvbDxCEnJqWnoYRlIAHi0IbxCDOAB6IrgAPQB+aSA

### PR DESCRIPTION
**Pull request by som-sm**
Fixes #1074.

<br>

Previously, `DelimiterCase` was not built using `Words`, so their behaviours with punctuations were different.
```ts
// v4.5
import type {Words, DelimiterCase} from "type-fest";

type T1 = Words<"onDialog::close">; // Punctuations cause split (kinda)
//   ^? type T1 = ["on", "Dialog", ":", ":close"]

type T2 = DelimiterCase<"onDialog::close", "-">; // No split on punctuations
//   ^? type T2 = "on-dialog::close"
```

<br>

But now, since `DelimiterCase` is built using `Words` and we want to avoid breaking changes, this PR includes a workaround to fix only the behaviour of `DelimiterCase`.

<br>

As mentioned in https://github.com/sindresorhus/type-fest/issues/1074#issuecomment-2698729943, in V5, IMO we should align this behaviour with Lodash. So, `Words<"onDialog::close">` should return  `["on", "Dialog", "close"]` and `KebabCase<"onDialog::close">` should return `on-dialog-close`.

### CODE REVIEW

**Comment by som-sm** [comment]
@filipw01 Would appreciate if you could give this a read!

File: source/internal/characters.d.ts [hunk 1]
```diff
@@ -31,3 +31,8 @@ export type Whitespace =
 	| '\u{FEFF}';
 
 export type WordSeparators = '-' | '_' | Whitespace;
+
+export type Punctuations =
```
Comment (filipw01) [inline source/internal/characters.d.ts:35]: Where does this list come from? Are we sure it's complete?

**Review by filipw01 — APPROVED** [review]

File: source/internal/characters.d.ts (hunk 1 above)
Comment (som-sm) [reply source/internal/characters.d.ts:35]: > Are we sure it's complete?

@filipw01 Not really, it's GPT generated.

Comment (sindresorhus) [inline source/internal/characters.d.ts:35]:
```suggestion
export type AsciiPunctuation =
```

File: source/internal/characters.d.ts [hunk 2]
```diff
@@ -31,3 +31,8 @@ export type Whitespace =
...
+  | '!' | '"' | '#' | '$' | '%' | '&' | '\'' | '(' | ')' | '*' | '+' | ',' | '-' | '.' | '/'
+  | ':' | ';' | '<' | '=' | '>' | '?' | '@' | '[' | '\\' | ']' | '^' | '_' | '`'
+  | '{' | '|' | '}' | '~';
```
Comment (sindresorhus) [inline source/internal/characters.d.ts:38]: One item per line and use tab-indentation.

**Review by sindresorhus — CHANGES_REQUESTED** [review]

File: source/internal/characters.d.ts (hunk 2 above)
Comment (som-sm) [reply source/internal/characters.d.ts]: Addressed in [399cf03](https://github.com/sindresorhus/type-fest/pull/1080/commits/399cf038f462866faf9bf6a52ba73fecdcb12c09).

File: source/internal/characters.d.ts (hunk 1 above)
Comment (som-sm) [reply source/internal/characters.d.ts]: Addressed in [399cf03](https://github.com/sindresorhus/type-fest/pull/1080/commits/399cf038f462866faf9bf6a52ba73fecdcb12c09).
