### PR TITLE
fix: `PartialOnUndefinedDeep` do not make unknown partial / only use LiteralKeys to reconstruct type

### LINKED ISSUE #756: PartialOnUndefinedDeep removes non-optional properties when the input type contains an index signature
Example:
```ts
import {PartialOnUndefinedDeep} from "type-fest"

type WithoutSignature = {
  foo: number
  bar: number | undefined
}
// Output1 contains the `foo` property
type Output1 = PartialOnUndefinedDeep<WithoutSignature>

type WithSignature = {
  foo: number
  bar: number | undefined
  [k: string]: unknown
}
// Output2 does not contain the `foo` property
type Output2 = PartialOnUndefinedDeep<WithSignature>
```
[TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwAoENbBQGwPIDsCquAJgKYBmwuJRAIiSWAL5xlQQhwBEMAnmCQFoyJAM4xOAKAm9+cAOrAYACwgBXGAGVgAc1woYqqCTgBeRBLgsIEAFxxcqkACMSUC3Cdo7D567gAfOFVickpqCUYJAHoouGx1MHUARjgAYwhcGBRKEThlYwADMmsCuDA2flgeaT5jeJhEmBSzVHQsPEJSCipaejAAHgVlNU0dPQMjAD5o2MsAPQB+KRljIaUtXX1DYzMEd2Lbe0cXN0tPKG9jv0DgrrCidwBtAGs7MShKbQBdO2Dn3AgAHdcBEZnEEuoAExwIgQUT2CDwdKZbK4PJKQoHUrlCCVXg1WT1RrQlpoGAYHAEELdah0BiDRTrMZbKZg+ZLIA)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/756">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/756/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by clemclx**
fix #756

- Do not treat unknown like undefined (the condition was `undefined extends T[KeyType]` that is true when `T[KeyType]` is `unknown`)
- The bug reported in #756 was due to the condition when reconstructing type (with `Merge`) to check if the key is present in the partial derived type (condition was always true if the index key type is string `KeyType extends keyof U` is always true). The new condition only check the literal keys of the partial derived type.

Note : this `LiteralKeyOf` type could be added to type-fest, it can be useful I think

### CODE REVIEW

**Comment by sindresorhus** [comment]
@Emiyaaaaa Looks good to you?

File: source/partial-on-undefined-deep.d.ts [hunk 1]
```diff
@@ -68,3 +70,8 @@ type PartialOnUndefinedDeepValue<T, Options extends PartialOnUndefinedDeepOption
 		: T extends Record<any, any> | undefined
 			? PartialOnUndefinedDeep<T, Options>
 			: unknown;
+
+/**
+Utility type to retrieve only literal keys from type.
+*/
+type LiteralKeyOf<T> = keyof {[K in keyof T as IsLiteral<K> extends true ? K : never]-?: never};
```
Comment (sindresorhus) [inline source/partial-on-undefined-deep.d.ts:77]: Can you move this to internal.d.ts? It makes it easier for us to keep track of what should probably be exported publicly.

File: test-d/partial-on-undefined-deep.ts [hunk 2]
```diff
@@ -49,6 +51,8 @@ expectAssignable<{
 	readonly1?: TestingType['readonly1'];
 	readonly2?: TestingType['readonly2'];
 	tuple?: TestingType['tuple'];
+	indexType: Partial<Pick<TestingType['indexType'], 'propertyB'>> & Omit<TestingType['indexType'], 'propertyB'>;
```
Comment (Emiyaaaaa) [inline test-d/partial-on-undefined-deep.ts:54]: It would be better to use expectType

```ts
declare const indexType: PartialOnUndefinedDeep<{[k: string]: string | undefined; propertyA: string; propertyB: string | undefined};>
expectType<{[k: string]?: string | undefined; propertyA: string; propertyB?: string | undefined}>(indexType)
```

File: test-d/partial-on-undefined-deep.ts [hunk 3]
```diff
@@ -49,6 +51,8 @@ expectAssignable<{
...
+	indexTypeUnknown: Partial<Pick<TestingType['indexTypeUnknown'], 'propertyB'>> & Omit<TestingType['indexTypeUnknown'], 'propertyB'>;
```
Comment (Emiyaaaaa) [inline test-d/partial-on-undefined-deep.ts:55]: Same as above

File: test-d/partial-on-undefined-deep.ts [hunk 4]
```diff
@@ -1,4 +1,4 @@
-import {expectAssignable} from 'tsd';
+import {expectAssignable, expectType} from 'tsd';
 import type {PartialOnUndefinedDeep} from '../index';
 
 type TestingType = {
```
Comment (Emiyaaaaa) [inline test-d/partial-on-undefined-deep.ts:4]: because changed the key type of object in this PR, so it would be better to check the property keyword like `readonly`

```ts
readonly readonlyProperty: string | undefined;
```

File: test-d/partial-on-undefined-deep.ts [hunk 5]
```diff
@@ -24,6 +24,8 @@ type TestingType = {
 	readonly2: ReadonlyArray<{propertyA: string; propertyB: number | undefined}> | undefined;
 	tuple: ['test1', {propertyA: string; propertyB: number | undefined}] | undefined;
 };
+declare const indexType: {[k: string]: string | undefined; propertyA: string; propertyB: string | undefined};
+declare const indexTypeUnknown: {[k: string]: unknown; propertyA: string; propertyB: number | undefined};
 
 // Default behavior, without recursion into arrays/tuples
 declare const foo: PartialOnUndefinedDeep<TestingType>;
```
Comment (Emiyaaaaa) [inline test-d/partial-on-undefined-deep.ts:31]: add 
```ts
readonly readonlyProperty?: TestingType['readonlyProperty'];
```

**Comment by sindresorhus** [comment]
Bump :)

**Comment by clemclx** [comment]
Hey, sorry for the delay. Let me know if there is something else to fix

**Comment by russelldavis** [comment]
@clemclx @sindresorhus it looks like this is ready to merge? (other than merge conflicts)
